name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5 matplotlib==3.7.1 seaborn==0.12.2 pandas==2.0.0
          pip install -e .
          pip install pytest

      - name: Run unit tests
        run: pytest

      - name: Run reconstruction tests (all approaches)
        run: python run_tests.py --approach all

      - name: List generated artifacts
        run: find artifacts -type f | sort

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reconstruction-matrices-and-visualizations
          path: |
            artifacts/*.png
            artifacts/*.txt
            artifacts/run_tests.log
      - name: Generate figures
        run: python generate_figures.py

      - name: Archive generated figures
        uses: actions/upload-artifact@v4
        with:
          name: thesis-figures
          path: artifacts/*.png

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set repository name in lowercase
        id: repo_lower
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.repo_lower.outputs.repo }}/explainability:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests inside Docker
        run: |
          mkdir -p artifacts
          docker run --rm -v $(pwd)/artifacts:/app/artifacts ghcr.io/${{ steps.repo_lower.outputs.repo }}/explainability:latest python run_tests.py --approach all
      
      - name: Archive Docker-generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-generated-artifacts
          path: artifacts/